# Generated by Django 5.0 on 2023-12-25 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event', max_length=100, unique=True, verbose_name='Title')),
                ('details', models.TextField(help_text='Details about the event', verbose_name='Details')),
                ('date', models.DateTimeField(help_text='When the event is planned to start', verbose_name='Date')),
                ('location', models.CharField(help_text='Where the event will be held', max_length=100, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this event entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the event entry was updated the last time')),
                ('attendees', models.ManyToManyField(help_text='Attendees of the event', related_name='attended_events', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(help_text='The creator of the event', on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
